# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16RIeDBunYI0NmmBsuvjcsMfEmSBrMRRa
"""

import pandas as pd
import numpy as np

df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN',
'londON_StockhOlm',
'Budapest_PaRis', 'Brussels_londOn'],
'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
'12. Air France', '"Swiss Air"']})

print(df.head())

df["FlightNumber"]=df["FlightNumber"].fillna(0)
df.head()
for i in range(len(df["FlightNumber"])):
  if(df["FlightNumber"][i]==0):
    df["FlightNumber"][i]=df["FlightNumber"][i-1]+10
print(df.head())

df[["from","to"]]=df.From_To.str.split("_",expand=True)
df.head()

for i in range(len(df["from"])):
  df["from"][i]=df["from"][i][0].upper()+df["from"][i][1:].lower()

for j in range(len(df["to"])):
  df["to"][j]=df["to"][j][0].upper()+df["to"][j][1:].lower()
print(df.head())

df=df.drop("From_To",axis=1)
print(df.head())

for i in range(len(df["RecentDelays"])):
  print(df["RecentDelays"][i])
  if(len(df["RecentDelays"][i])<3):
    for j in range(0,3-len(df["RecentDelays"][i])):
      df["RecentDelays"][i].append("NaN")
print(df["RecentDelays"])

d2 = (pd.DataFrame(df['RecentDelays'].values.tolist(), index=df.index)
        .rename(columns = lambda x: 'Delay{}'.format(x+1)))
print(d2)
df=df.join(d2)
print(df.head())
df.drop("RecentDelays",axis=1)

print(df["Delay1"].isnull)

